language: ruby
dist: focal
rvm:
  - 2.7.1
  - 2.6.6
  - 2.5.8
  - 3.0.2
before_install:
  - gem install bundler undercover
  - gem update --system
script:
  - bundle exec rake
  - git pull origin master:master
  - undercover --compare master
