language: ruby
rvm:
  - 2.6.2
  - 2.5.5
  - 2.4.5
  - 2.3.7
before_install:
  - gem install bundler undercover
  - gem update --system
script:
  - bundle exec rake
  - git pull origin master:master
  - undercover --compare master
